In [1]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [2]:
x = 3
print(type(x)) 
print(x + 1)   
print(x - 1)   
print(x * 2)   
print(x ** 2) 
x += 1
print(x)
x *= 2
print(x) 
y = 2.5
print(type(y)) 
print(y + 1)
print(y*5)


<class 'int'>
4
2
6
9
4
8
<class 'float'>
3.5
12.5


In [3]:
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t == f)

<class 'bool'>
False
True
False
False


In [4]:
s = "ramya"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('m', 'ma'))
print(' world '.strip())


Ramya
RAMYA
  ramya
 ramya 
ramaya
world


In [5]:
l = [1,2,3]
print(l[1])
print(l[-1])
l[2] = 'ram'
print(l)
l.append('hi')
print(l)
x = l.pop()
print(x, l)

2
3
[1, 2, 'ram']
[1, 2, 'ram', 'hi']
hi [1, 2, 'ram']


In [6]:
nums = list(range(7))   
print(nums) 
print(nums[2:4]) 
print(nums[:2])  
print(nums[:-1])  
nums[2:4] = [8, 9]    
print(nums)

[0, 1, 2, 3, 4, 5, 6]
[2, 3]
[0, 1]
[0, 1, 2, 3, 4, 5]
[0, 1, 8, 9, 4, 5, 6]


In [7]:
for i in nums:
    print(i)

0
1
8
9
4
5
6


In [8]:
for idx, i in enumerate(nums):
    print("%d: %d" %(idx+1, i))

1: 0
2: 1
3: 8
4: 9
5: 4
6: 5
7: 6


In [9]:
d = {'cat': 'cute', 'dog': 'furry'}
print(d['cat']) 
print('cat' in d)
d['fish'] = 'wet'
print(d)
print(d.get('monkey', 'N/A'))

print(d.get('fish', 'N/A'))
del d['fish']  
print(d.get('fish', 'N/A')) 

cute
True
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}
N/A
wet
N/A


In [10]:
for i, j in d.items():
    print(i,j)

cat cute
dog furry


In [11]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy

In [13]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))  
print(a.shape)    
print(a[0], a[1], a[2])  
a[0] = 5  
print(a)
b = np.array([[1,2,3],[4,5,6]])  
print(b.shape) 

print(b[0, 0], b[0, 1], b[1, 0])


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [14]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :] 
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) 
print(col_r2, col_r2.shape) 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [15]:
%autosave 5

Autosaving every 5 seconds


In [16]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)
print(bool_idx) 

print(a[bool_idx]) 

print(a[a > 2]) 

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [17]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [18]:
import numpy as np

x = np.array([1, 2.5]) 
print(x.dtype)  

float64


In [19]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print(x * y)
print(np.multiply(x, y))


print(x / y)
print(np.divide(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [20]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x, v))


print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
pip install scipy

In [ ]:
pip install imread

In [ ]:
from scipy.misc import imread, imsave, imresize

img = imread('animal.webp')
print(img.dtype, img.shape)
img_tinted = img * [1, 0.95, 0.9]
img_tinted = imresize(img_tinted, (300, 300))
imsave('animal.webp', img_tinted)